name: Versions
# on:
#   schedule:
#   - cron: "0 0 * * *"

on:
  push:
    paths:
      - .github/workflows/versions.yml
      - tools/upgrade.bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Review and upgrade the dependencies
        uses: docker://ubuntu:focal
        with:
          args: "bash tools/upgrade.bash"
      - name: Commit the dependency changes
        uses: cardboardci/github-actions/auto-commit@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: '/pkglist'
          MESSAGE: 'Upgrade packages to latest ubuntu dependencies'
          PULL_REQUEST_TITLE: 'Bump image dependencies to latest'