name: Versions
on:
  push:
    branches:
      - master
    paths:
    - .github/actions/dependencies/Dockerfile
    - .github/actions/dependencies/entrypoint.sh
    - .github/workflows/versions.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Upgrade the dependencies
        uses: ./.github/actions/dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}